"""Shell completion, generated from the parser itself.

Hand-written completion scripts rot. Someone adds a flag, forgets the bash
file, and the completion quietly disagrees with the tool - which is worse than
having none, because now Tab actively misleads you.

So these are walked out of the live ``argparse`` tree. Add a subcommand and its
completion exists; rename a flag and the old one stops being offered. The only
thing written by hand is the shape of each shell's syntax.

Saved server names are completed dynamically by shelling out to
``tessera servers list --names``, so ``tessera status <Tab>`` offers your
actual servers.
"""

from __future__ import annotations

import argparse
from typing import Dict, List, Tuple


def _walk(parser: argparse.ArgumentParser) -> Tuple[List[str], Dict[str, List[str]]]:
    """Return (global flags, {subcommand: flags})."""
    globals_: List[str] = []
    subs: Dict[str, List[str]] = {}
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            for name, sub in action.choices.items():
                flags: List[str] = []
                for sub_action in sub._actions:
                    flags.extend(sub_action.option_strings)
                subs[name] = sorted(set(flags))
        else:
            globals_.extend(action.option_strings)
    return sorted(set(globals_)), subs


#: Subcommands whose first positional is a target, so it should complete to
#: saved server names.
TARGET_FIRST = ["install", "status", "audit", "uninstall", "doctor", "adopt",
                "verify", "backup", "watch"]


def render(shell: str, parser: argparse.ArgumentParser) -> str:
    globals_, subs = _walk(parser)
    if shell == "bash":
        return _bash(globals_, subs)
    if shell == "zsh":
        return _zsh(globals_, subs)
    if shell == "fish":
        return _fish(globals_, subs)
    raise ValueError("unsupported shell: {}".format(shell))


def _bash(globals_: List[str], subs: Dict[str, List[str]]) -> str:
    cases = "\n".join(
        '        {})\n            opts="{}"\n            ;;'.format(
            name, " ".join(flags))
        for name, flags in sorted(subs.items()))
    return '''# tessera bash completion - generated by 'tessera completions bash'
# Install:  tessera completions bash > /etc/bash_completion.d/tessera
_tessera() {{
    local cur prev cmd opts servers
    COMPREPLY=()
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"
    cmd="${{COMP_WORDS[1]}}"

    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "{cmds} {globals}" -- "$cur") )
        return 0
    fi

    case "$cmd" in
{cases}
        *)
            opts="{globals}"
            ;;
    esac

    # Second word of a target-taking command: offer saved servers.
    case "$cmd" in
        {targets})
            if [ "$COMP_CWORD" -eq 2 ] && [[ "$cur" != -* ]]; then
                servers=$(tessera servers list --names 2>/dev/null)
                COMPREPLY=( $(compgen -W "$servers local demo" -- "$cur") )
                return 0
            fi
            ;;
    esac

    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
    return 0
}}
complete -F _tessera tessera
'''.format(cmds=" ".join(sorted(subs)), globals=" ".join(globals_),
           cases=cases, targets="|".join(TARGET_FIRST))


def _zsh(globals_: List[str], subs: Dict[str, List[str]]) -> str:
    lines = []
    for name, flags in sorted(subs.items()):
        opts = " ".join("'{}'".format(f) for f in flags)
        lines.append("    {})\n      _arguments {} '*:server:__tessera_servers'\n      ;;".format(name, opts))
    return '''#compdef tessera
# tessera zsh completion - generated by 'tessera completions zsh'
# Install:  tessera completions zsh > "${{fpath[1]}}/_tessera"

__tessera_servers() {{
  local -a servers
  servers=(${{(f)"$(tessera servers list --names 2>/dev/null)"}} local demo)
  _describe 'server' servers
}}

_tessera() {{
  local context state line
  typeset -A opt_args

  _arguments -C \\
    '1:command:(({cmds}))' \\
    '*::arg:->args'

  case "$words[1]" in
{cases}
  esac
}}
_tessera "$@"
'''.format(cmds=" ".join(sorted(subs)), cases="\n".join(lines))


def _fish(globals_: List[str], subs: Dict[str, List[str]]) -> str:
    out = ["# tessera fish completion - generated by 'tessera completions fish'",
           "# Install:  tessera completions fish > "
           "~/.config/fish/completions/tessera.fish",
           "",
           "function __tessera_servers",
           "    tessera servers list --names 2>/dev/null",
           "    echo local",
           "    echo demo",
           "end",
           ""]
    for name in sorted(subs):
        out.append("complete -c tessera -n '__fish_use_subcommand' "
                   "-a '{}'".format(name))
    out.append("")
    for name in TARGET_FIRST:
        if name in subs:
            out.append("complete -c tessera -n '__fish_seen_subcommand_from {}' "
                       "-a '(__tessera_servers)'".format(name))
    out.append("")
    for name, flags in sorted(subs.items()):
        for flag in flags:
            if flag.startswith("--"):
                out.append("complete -c tessera -n "
                           "'__fish_seen_subcommand_from {}' -l {}".format(
                               name, flag.lstrip("-")))
    return "\n".join(out) + "\n"
